### PR TITLE
Unresponsive links

### LINKED ISSUE #11: 404 errors in multiple links
In sec_licensing_existing_communities.html all highlighted links give a 404 error.
image

### PR DESCRIPTION
**Pull request by thaopham03**
Fixed #11 
Reviewed by Nega

### CODE REVIEW

**Comment by pearcej** [comment]
Thanks, @thaopham03 for the corrected URLs

**Comment by pearcej** [comment]
@demekenega can you please review this by checking all links and also checking the accuracy of all the visual attributes, which are used for screen readers?

**Comment by demekenega** [comment]
@pearcej, sure, I will do that.

**Comment by thaopham03** [comment]
@pearcej Hello Dr. Jan, me and @demekenega have fixed the issue. You could double check it again, thank you so much!

**Pull request merged**
