### PR TITLE
Wordsmith self-check question section 4.2

### PR DESCRIPTION
**Pull request by thaopham03**
Reviewed by @NelsonXunic

### CODE REVIEW

**Review by NelsonXunic — APPROVED** [review]
Reviewed by @NelsonXunic

**Comment by pearcej** [comment]
I don't love this question. For one, I thought we discussed using fill-in the blank for this kind of question which is just recall of a term. For another, I think the wrong answers are too obviously wrong.

**Comment by thaopham03** [comment]
Hi Dr. @pearcej, Nelson, Nega and I have modified this question into a Parson problem. Feel free to leave any feedback.

**Comment by pearcej** [comment]
Very creative!

**Pull request merged**
