### PR TITLE
I added the console term to the Appendices.

### LINKED ISSUE #249: Add "console" term to Text Index in Appendices

### PR DESCRIPTION
**Pull request by timalsinab**
Fix #249
Reviewed by @tapiae1

### CODE REVIEW

**Comment by pearcej** [comment]
@timalsinab You have multiple issues on a single branch. Please fix.

**Comment by pearcej** [comment]
@timalsinab This has merge conflicts. Please update your branch and resolve all conflcts.

**Comment by pearcej** [comment]
@timalsinab Please respond.

**Comment by timalsinab** [comment]
@pearcej Apologies for not replying earlier. I fixed the merge conflict. Can you please review it?

**Comment by pearcej** [comment]
@timalsinab I noted that your branch name did not match the issue you asked to close. One is #255 which is irrelevant to this issue. Please use better branch names.

**Pull request merged**
