### PR TITLE
Grammatical error

### LINKED ISSUE #21: Grammatical error
2.4 OSS Community Communication (location: sec_community_communication.html)
“Synchronous communications typically includes various forms of audio/video chat, which is neither convenient nor efficient for widely dispersed OSS communities.” => “includes” should be “include”

### PR DESCRIPTION
**Pull request by demekenega**
fixes #21 
Reviewed by: @eygul

### CODE REVIEW

**Comment by pearcej** [comment]
@demekenega Are you making a new branch from the main branch for each issue because this pull request has extra files that should not be in it.

**Comment by demekenega** [comment]
@pearcej Yes, I am making all my branches from my central unit.

**Comment by pearcej** [comment]
In the future, please be more specific about exactly what "grammatical error" you are correcting.

**Comment by demekenega** [comment]
@pearcej Thank you for the feedback. I will do that next time.

**Pull request merged**
