### PR TITLE
Add git fetch to index

### PR DESCRIPTION
**Pull request by IsaacSGray**
I had accidentally worked on main. Created a branch and packed up to my room. I had a crash and had to restart my Laptop and forgot to swap back as I worked. I kept my work up to avoid any merge conflicts.

### CODE REVIEW

**Comment by pearcej** [comment]
@IsaacSGray This set of tags is not in the correct position. The <idx> tags need to be INSIDE of the paragraph in which the term is used. 

Also, why are the <h> tags embedded inside the <idx> tags?

**Comment by IsaacSGray** [comment]
I did not know embedded tags were taboo or not allowed. I can get to work correcting this- thank you for notifying me.

**Comment by pearcej** [comment]
@IsaacSGray It is not that you can't nest tags. Obviously you can when it is needed, but it doesn't look like you understand what /<h/> does. I was asking a real question above. Why are you using /<h/> tags?

See https://pretextbook.org/doc/guide/html/the-index.html
image

Then remove the /<h/> tags, recommit to this same branch, and then ping me.

**Comment by pearcej** [comment]
Also, the \<idx\> tags need to be INSIDE the paragraph where the term is discussed, as mentioned in my comment above. Please change this as well.

**Comment by IsaacSGray** [comment]
There was a paragraphs ID which overrides any other tag such as <p> and any idx placed in a section labeled paragraphs will default to indexing the entire section. Commented out the paragraphs tag and compiled correctly and indexed correctly. 

Kudos to Dameke for helping me notice this. @pearcej

**Comment by IsaacSGray** [comment]
Closed this. Opening new issue.

**Pull request closed without merging**
