### PR TITLE
Fix #152 by reducing the text in the symbol index list

### LINKED ISSUE #152: In the list of symbols, some symbols index too much text

### PR DESCRIPTION
**Pull request by thaopham03**
Fix #152 
Reviewed by Moise

### CODE REVIEW

**Comment by pearcej** [comment]
@thaopham03 Please make sure this compiles correctly on your local. Then commit again to this same branch. And, post in the note the Github username of the person who reviewed your pull request.

**Comment by thaopham03** [comment]
> @thaopham03 Please make sure this compiles correctly on your local. Then commit again to this same branch. And, post in the note the Github username of the person who reviewed your pull request.

Hello Dr. Jan, I have fixed the issue and complied successfully in my local. Thank you so much!

**Comment by pearcej** [comment]
@thaopham03 Now you are committing 41 files which are mostly log files. Please update your branch and local then revert your last commit and then ONLY commit the single file that you changed!

**Comment by pearcej** [comment]
@thaopham03 please update your branch and then notify me

**Comment by thaopham03** [comment]
I have updated my branch Dr. @pearcej

**Comment by pearcej** [comment]
@thaopham03 Please see the TA. This still has several errors and is not ready. I think you need assistance.

**Comment by thaopham03** [comment]
Close this pull request as it appears to be too messy and not be able to merge onto the main.

**Pull request closed without merging**
