### PR TITLE
Add 'history' to Bash Shell Cheat Sheet and Basic Shell Commands

### LINKED ISSUE #250: Add "grep" and "history" to Bash Shell Cheat Sheet
'grep' and 'history' are useful shell commands that should be added to the cheat sheet.

### PR DESCRIPTION
**Pull request by Boorclark**
### Description
This PR enhances the **Bash Shell Cheat Sheet**  and **Basic Shell Commands** by adding the 'history' command.

### Testing
1. Navigate to Section 7 of the _Open Source_ textbook, where the **Bash Shell Cheat Sheet** is located.
2. Head to the **The Basics: Reading, Writing, Counting, etc.** section, where you should now find the 'history' command along with a clear and informative explanation.
3. Navigate to the **Basic Shell Commands** in Section 3.
4. Make sure you see the paragraph on history and that it is explained well.
---
| Bash Shell Cheat Sheet | Basic Shell Commands |
|----------------|-------------------|
| image | image |

fixes #250

### CODE REVIEW

**Comment by pearcej** [comment]
@Boorclark Thanks!  I like the idea of history a lot. Can you find an appropriate place to add that to https://runestone.academy/ns/books/published/bc_opensource_f23/sec_dev_basic_shell_commands.html where the flow works well?

I thought about grep and still am not convinced since the book is intended for beginners. What I am wondering about is whether the search in VSCode suffices?  What are your thoughts?

**Comment by Boorclark** [comment]
@pearcej Thank you for the feedback! I currently already have 'history' in **The Basics: Reading, Writing, Counting, etc.** section. Did you want me to move this to another location on that webpage?

In regard to `grep` I thought this was useful because if another school  or person intends to use the book then they may not use VSCode and we want people to stray away from resulting to a UI. However, I think almost everyone uses `ctrl + f ` and `ctrl + Shift + f` so I am not against the idea of doing away with it. 

The only reason I am for keeping it is because we have other things like `mkdir` and we could also say that adding a file in VSCode would suffice (however I think knowing the bash command for that is way more useful than `grep`).

**Comment by pearcej** [comment]
I am confused because on this pull request, I only see changes to the appendix regarding `history`. I am recommending changes to sec_dev_basic_shell_commands.ptx also

**Comment by pearcej** [comment]
@Boorclark thoughts?

**Comment by Boorclark** [comment]
@pearcej I updated the PR so you can see new testing instructions. I deleted **grep** and added history to the **Basic Shell Commands** section. Thank you for bearing with my confusion.

**Pull request merged**
