### PR TITLE
Wordsmith self-check question section 6.4

### LINKED ISSUE #174: Self-check question section 6.4

### PR DESCRIPTION
**Pull request by eygul**
fix #174

### CODE REVIEW

**Review by thaopham03 — COMMENTED** [review]
Everything works fine for me!

**Comment by pearcej** [comment]
@eygul @thaopham03 This self-check question is too obvious. I think anyone could likely guess correctly without having read, so it gives too little incentive for reading.

I am not convinced it is fixable since "bug triage" gives it away entirely.

**Comment by eygul** [comment]
@pearcej I replaced the question with a new one.

**Comment by pearcej** [comment]
@eygul much better! Thanks!

**Pull request merged**
